"use client";
import { useEffect, useState } from "react";
import { useParams, useRouter } from "next/navigation";
import { supabase } from "../../../services/supabaseClient";
import { 
  ChevronLeft, 
  Star, 
  Quote, 
  Download, 
  CheckCircle2, 
  Clock, 
  User,
  FileText
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Skeleton } from "@/components/ui/skeleton";

export default function TestimonialPage() {
  const { id } = useParams();
  const router = useRouter();
  const [data, setData] = useState<any>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetchInterviewData = async () => {
      const { data, error } = await supabase
        .from("interviews")
        .select("*")
        .eq("id", id)
        .single();

      if (data) setData(data);
      setLoading(false);
    };

    fetchInterviewData();
  }, [id]);

  if (loading) return <TestimonialSkeleton />;

  return (
    <div className="min-h-screen bg-[#0a0a0a] text-white p-6 lg:p-12">
      <div className="max-w-4xl mx-auto">
        {/* Header Navigation */}
        <div className="flex items-center justify-between mb-8">
          <Button 
            variant="ghost" 
            onClick={() => router.push('/')} 
            className="text-zinc-400 hover:text-black flex gap-2 p-0 cursor-pointer"
          >
            <ChevronLeft className="size-4" /> Back to Dashboard
          </Button>
          {/* <Button className="bg-[#2dd4bf] hover:bg-[#26b2a1] text-black font-semibold flex gap-2">
            <Download className="size-4" /> Export Report
          </Button> */}
        </div>

        <main className="space-y-8">
          {/* Profile & Score Section */}
          <section className="flex flex-col md:flex-row md:items-end justify-between gap-6 border-b border-zinc-800 pb-8">
            <div className="space-y-2">
              <Badge className="bg-[#2dd4bf]/10 text-[#2dd4bf] hover:bg-[#2dd4bf]/10 mb-2">
                Interview Completed
              </Badge>
              <h1 className="text-4xl font-bold">{data?.candidate_name}</h1>
              {/* <p className="text-zinc-400 text-lg flex items-center gap-2">
                Candidate for <span className="text-white underline decoration-[#2dd4bf] underline-offset-4">{data?.candidate_role}</span>
              </p> */}
            </div>

            <div className="bg-[#141414] p-6 rounded-2xl border border-zinc-800 flex items-center gap-6">
              <div className="text-center">
                <p className="text-zinc-500 text-xs uppercase tracking-widest mb-1 font-bold">Overall Score</p>
                <div className="flex items-center gap-2">
                  <span className="text-4xl font-bold text-[#2dd4bf]">{data?.overall_score || "N/A"}</span>
                  <span className="text-zinc-600">/ 5.0</span>
                </div>
              </div>
              <div className="h-10 w-[1px] bg-zinc-800" />
              <div className="flex gap-1">
                {[1, 2, 3, 4, 5].map((star) => (
                  <Star 
                    key={star} 
                    className={`size-5 ${star <= Math.round(data?.overall_score || 0) ? 'text-[#2dd4bf] fill-[#2dd4bf]' : 'text-zinc-700'}`} 
                  />
                ))}
              </div>
            </div>
          </section>

          {/* AI Generated Testimonial */}
          <section>
            <Card className="bg-gradient-to-br from-[#141414] to-[#0d0d0d] border-zinc-800 text-white shadow-2xl relative overflow-hidden">
               <Quote className="absolute -top-4 -right-4 size-32 text-zinc-800/20 rotate-12" />
               <CardHeader>
                 <CardTitle className="text-zinc-400 text-sm uppercase tracking-wider flex items-center gap-2">
                   <CheckCircle2 className="size-4 text-[#2dd4bf]" /> AI Recruiter Summary
                 </CardTitle>
               </CardHeader>
               <CardContent>
                 <p className="text-xl leading-relaxed font-light text-zinc-200">
                    "{data?.testimonial_summary || "The summary is being generated by our AI agent..."}"
                 </p>
               </CardContent>
            </Card>
          </section>

          {/* Tabs for Transcript and Resume */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
            <Card className="bg-[#141414] border-zinc-800 text-white">
              <CardHeader className="border-b border-zinc-800">
                <CardTitle className="text-sm flex items-center gap-2">
                  <FileText className="size-4 text-zinc-500" /> Interview Transcript
                </CardTitle>
              </CardHeader>
              <CardContent className="p-0 max-h-[400px] overflow-y-auto">
                <div className="p-4 space-y-4">
                  {data?.transcript ? (
                    <div className="text-sm text-zinc-400 font-mono whitespace-pre-wrap leading-relaxed">
                      {JSON.stringify(data.transcript, null, 2)}
                    </div>
                  ) : (
                    <p className="text-zinc-600 italic text-sm">No transcript available for this session.</p>
                  )}
                </div>
              </CardContent>
            </Card>

            <div className="space-y-6">
              <Card className="bg-[#141414] border-zinc-800 text-white">
                <CardHeader>
                  <CardTitle className="text-sm">Quick Details</CardTitle>
                </CardHeader>
                <CardContent className="space-y-4">
                  <div className="flex justify-between text-sm">
                    <span className="text-zinc-500 flex items-center gap-2"><Clock className="size-4" /> Date</span>
                    <span>{new Date(data?.created_at).toLocaleDateString()}</span>
                  </div>
                  <div className="flex justify-between text-sm">
                    <span className="text-zinc-500 flex items-center gap-2"><User className="size-4" /> Status</span>
                    <span className="text-[#2dd4bf]">Verified AI Testimonial</span>
                  </div>
                </CardContent>
              </Card>

              <div className="p-6 rounded-2xl bg-[#2dd4bf]/5 border border-[#2dd4bf]/20">
                <h4 className="text-[#2dd4bf] font-semibold mb-2 text-sm">Hiring Recommendation</h4>
                <p className="text-xs text-zinc-400 leading-relaxed">
                  This score is based on a technical assessment of React, Next.js, and communication skills. 
                  Please review the full transcript for behavioral insights.
                </p>
              </div>
            </div>
          </div>
        </main>
      </div>
    </div>
  );
}

function TestimonialSkeleton() {
  return (
    <div className="min-h-screen bg-[#0a0a0a] p-12 max-w-4xl mx-auto space-y-8">
      <Skeleton className="h-6 w-32 bg-zinc-800" />
      <div className="flex justify-between items-end">
        <div className="space-y-3">
          <Skeleton className="h-4 w-24 bg-zinc-800" />
          <Skeleton className="h-12 w-64 bg-zinc-800" />
          <Skeleton className="h-6 w-48 bg-zinc-800" />
        </div>
        <Skeleton className="h-24 w-48 bg-zinc-800 rounded-2xl" />
      </div>
      <Skeleton className="h-48 w-full bg-zinc-800 rounded-3xl" />
    </div>
  );
}